[project]
name = 'vision-math'
experiment_name = 'baseline_run'

[data]
raw_dir = 'data/raw'
split_dir = 'data/splits'
batch_size = 32
num_workers = 4
image_size = [128,128]
seed = 777

[model]
architecture = 'vision_transformer'
num_layers = 4
dropout = 0.1
dim_ratio = 4
patch_size = 16
num_heads = 4
max_seq_len = 6
n_embd = 256

[training]
lr = 1e-4
max_steps = 2000
warmup_steps = 500
weight_decay = 0.01
betas = [0.9, 0.95]
grad_clip = 1.0
val_every_steps = 500
vis_every_steps = 500
scheduler = 'cosine'


[logging]
use_wandb = true
project_name = 'vision_model_1'
assets_dir = 'assets'

